app/PucMigos/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('usuarios/', include('usuarios.urls')),

]

app/homepage/urls.py
from django.urls import path
from . import views

app_name = "homepage"

urlpatterns = [
    path('', views.home_view, name='home'),
]

app/usuarios/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static



app_name = 'usuarios'

urlpatterns = [
    path('plataforma/', views.plataforma, name='plataforma'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('perfil/', views.perfil, name='perfil'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# Adicione esta configuração ao final do arquivo urls.py principal
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from .models import Usuarios, Perfil, Like
from django.core.files.storage import FileSystemStorage
from django.conf import settings 
from django.http import JsonResponse
from django.contrib import messages
import os
from django.db import IntegrityError

# Create your views here.

def login(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, username=email, password=password)
        if user is not None:
            auth_login(request, user)
            return redirect('homepage:home')
        else:
            return render(request, 'login-page.html', {'error': 'Invalid login credentials.'})
    else:
        return render(request, 'login-page.html')

@login_required
def logout(request):
    auth_logout(request)
    return redirect('homepage:home')


def signup(request):
    if request.method == 'POST':
        usuario_email = Usuarios.objects.filter(email=request.POST['email']).first()
        usuario_nome = Usuarios.objects.filter(nome=request.POST['nome']).first()
        if usuario_email or usuario_nome:
            return render(request, 'signup-page.html', {'error': 'Já existe um usuário com o mesmo e-mail ou mesmo nome'})

        nome = request.POST.get('nome')
        email = request.POST.get('email')
        cpf = request.POST.get('cpf')
        cep = request.POST.get('cep')
        estado = request.POST.get('estado')
        cidade = request.POST.get('cidade')
        bairro = request.POST.get('bairro')
        rua = request.POST.get('rua')
        matricula = request.POST.get('matricula')
        curso = request.POST.get('curso')
        data_de_nascimento = request.POST.get('data_de_nascimento')
        senha = request.POST.get('senha')
        confirmar_senha = request.POST.get('confirmar_senha')

        if senha != confirmar_senha:
            return render(request, 'signup-page.html', {'error': 'As senhas não são iguais.'})
        
        if Usuarios.objects.filter(matricula=matricula).exists():
            return render(request, 'signup-page.html', {'error': 'Matricula already exists.'})

        newUser = Usuarios.objects.create_user(
            email=email, 
            password=senha,
            cep=cep,
            estado=estado,
            cidade=cidade,
            bairro=bairro,
            rua=rua, 
            nome=nome, 
            cpf=cpf, 
            matricula=matricula, 
            curso=curso, 
            data_de_nascimento=data_de_nascimento
        )
        newUser.save()
        return redirect('homepage:home')

    else: 
        return render(request, 'signup-page.html')

@login_required
def plataforma(request):
    usuario = request.user
    
    # Exclui os usuários que já receberam like ou dislike do usuário atual
    usuarios_excluidos = list(Like.objects.filter(usuario_que_deu_like=usuario).values_list('usuario_que_recebeu_like', flat=True))
    usuarios_excluidos.append(usuario.id)  # Adiciona o próprio usuário
    
    perfis = Perfil.objects.exclude(usuario=usuario).exclude(id__in=usuarios_excluidos)

    if request.method == 'POST':
        perfil_id = request.POST.get('perfilId')
        acao = request.POST.get('acao')  # 'like' ou 'dislike'

        if acao in ['like', 'dislike'] and perfil_id:
            try:
                usuario_que_recebeu_like = Usuarios.objects.get(id=perfil_id)
                
                # Cria um novo registro de like/dislike
                like = Like.objects.create(
                    usuario_que_deu_like=usuario, 
                    usuario_que_recebeu_like=usuario_que_recebeu_like,
                    # Remova acao, pois isso não é um campo do modelo Like
                )
                
                # Retorna uma mensagem de sucesso para requisições AJAX
                if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                    return JsonResponse({'message': f'{acao.capitalize()} registrado com sucesso'}, status=200)
                else:
                    # Redireciona ou retorna uma resposta apropriada para requisições normais (não AJAX)
                    return redirect('plataforma')
            
            except Usuarios.DoesNotExist:
                return JsonResponse({'error': 'Usuário não encontrado'}, status=404)
            except IntegrityError:
                return JsonResponse({'error': 'Ocorreu um erro ao processar seu like'}, status=400)

    # Lógica para obter usuários para apresentação
    likes_dados = Like.objects.filter(usuario_que_deu_like=usuario).values_list('usuario_que_recebeu_like', flat=True)
    likes_recebidos = Like.objects.filter(usuario_que_recebeu_like=usuario).values_list('usuario_que_deu_like', flat=True)

    matches_mutuos_ids = set(likes_dados).intersection(set(likes_recebidos))
    matches_mutuos = Usuarios.objects.filter(id__in=matches_mutuos_ids)
    outros_usuarios = Usuarios.objects.exclude(id=usuario.id).exclude(id__in=matches_mutuos_ids)

    usuarios_para_apresentacao = list(matches_mutuos) + list(outros_usuarios)
    
    # Verifica se a requisição é AJAX
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        # Retorna apenas os dados necessários em formato JSON para AJAX
        data = {
            'usuarios_para_apresentacao': [{'id': u.id, 'nome': u.nome} for u in usuarios_para_apresentacao],
            'perfis': list(perfis.values('id', 'descricao'))
        }
        return JsonResponse(data)
    else:
        # Renderiza o template HTML normalmente para requisições não AJAX
        return render(request, 'plataforma.html', {
            'usuarios_para_apresentacao': usuarios_para_apresentacao, 
            'perfis': perfis
        })



@login_required
def perfil(request):
    try:
        user_profile = request.user.perfil
    except Perfil.DoesNotExist:
        user_profile = Perfil.objects.create(usuario=request.user)

    # Synchronize birth date
    if user_profile.data_de_nascimento != request.user.data_de_nascimento:
        user_profile.data_de_nascimento = request.user.data_de_nascimento
        user_profile.save()

    # Prepare initial context
    context = {
        'nome': request.user.nome,
        'data_de_nascimento': request.user.perfil.data_de_nascimento,
        'descricao': user_profile.descricao if user_profile.descricao else '',
        'foto': user_profile.foto_url_modificado() if user_profile.foto else None,
        'sexo': user_profile.get_sexualidade_display() if user_profile.sexualidade else None,
    }

    if request.method == 'POST':
        descricao = request.POST.get('descricao')
        foto = request.FILES.get('foto')
        sexo = request.POST.get('sexo')

        user_profile.descricao = descricao
        user_profile.sexualidade = sexo  # Atualiza o campo sexualidade

        if foto:
            user_profile.foto = foto

        user_profile.save()

        # Update context with new or existing values
        context.update({
            'descricao': descricao,
            'foto': user_profile.foto.url if user_profile.foto else None,
            'sexo': user_profile.get_sexualidade_display() if user_profile.sexualidade else None,
        })

        return render(request, 'plataforma.html', context)  # Redireciona para evitar resubmissão do formulário

    return render(request, 'profile-page.html', context)

app/usuarios/templates/login-page.html
{% load static %} 
{% block static %}
<link rel="stylesheet" href="{% static 'usuarios/login-page.css' %}"> 
{% endblock %}
{% block content %}
<body>
    <div class="main-login">
        <div class="left-login">
            <h1>Faça login <br> E Junte-se ao PucMatch</h1>
            <img src="{% static 'usuarios/imagemanimada.svg' %}" class="left-login-image" alt="imagem">
        </div>
        <div class="right-login">
            <form action="{% url 'usuarios:login' %}" method="post">
                {% csrf_token %}
                <div class="card-login">
                    {% if error %}
                        <p class="error">{{ error }}</p>
                    {% endif %}
                    <div class="textfield">
                        <label for="email">Email</label>
                        <input type="text" name="email" placeholder="Email">
                    </div>
                    <div class="textfield">
                        <label for="Senha">Senha</label>
                        <input type="password" name="password" placeholder="Senha">
                    </div>
                    <button class="btn-login" >login</button>
                </form>
            </div>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}

app/usuarios/templates/plataforma.html
{% load static %} 
{% block static %}
<link rel="stylesheet" href="{% static 'usuarios/plataforma.css' %}"> 
<script src="https://unpkg.com/@phosphor-icons/web"></script>
<meta name="csrf-token" content="{{ csrf_token }}">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

{% endblock %}
{% block content %}

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <div id="left-items">
                            <img class="navbar-brand" src="{% static 'usuarios/logo_1.png' %}" alt="">
                                <li class="nav-item">
                                    <button class="nav-button">
                                        <a class="nav-link" href="{% url 'homepage:home' %}">Home</a>
                                    </button>
                                </li>
                        </div>
                            <div id="right-items">
                                <li class="nav-item">
                                    <button class="nav-button">
                                        <a class="nav-link" href="{% url 'usuarios:perfil' %}">Perfil</a>
                                    </button>
                                </li>
                                <li class="nav-item">
                                    <button class="nav-button">
                                        <a class="nav-link" href="{% url 'usuarios:logout' %}">Logout</a>
                                    </button>
                                </li>
                            </div>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <div class="container-image">
            <div class="container-images">
                {% for perfil in perfis %}
                <form action="{% url 'usuarios:plataforma' %}" method="POST" class="perfil-form" data-action-url="{% url 'usuarios:plataforma' %}" id="perfil-{{ perfil.usuario.id }}">
                    {% csrf_token %}
                    <figure class="figure" id="perfil-{{ perfil.usuario.id }}" >
                        {% if perfil.foto %}
                        <img src="{{ perfil.foto_url_modificado }}" alt="Foto de perfil" class="figure-img">
                        {% else %}
                        <img src="" alt="Default Image">
                        {% endif %}
                        <div class="centered-text">
                            <div class="blur-background">
                                <h4>{{ perfil.usuario.nome }}</h4>
                                <p>{{ perfil.idade }}</p>
                                <p>{{ perfil.descricao }}</p>
                            </div>
                        </div>
                        <figcaption class="figure-caption">
                            <button class="like" type="button" data-perfil-id="{{ perfil.usuario.id }}" data-acao="like">
                                <i class="ph ph-heart"></i> Like
                            </button>
                            <button class="dislike" type="button" data-perfil-id="{{ perfil.usuario.id }}" data-acao="dislike">
                                <i class="ph ph-x"></i> Dislike
                            </button>
                        </figcaption>
                        <input type="hidden" name="perfilId" value="{{ perfil.usuario.id }}">
                    </figure>
                </form>
                {% endfor %}
            </div>
        </div>
    </main>
  </body>
</html>
<script>
    document.querySelectorAll('.like, .dislike').forEach(button => {
        button.addEventListener('click', function() {
            const form = this.closest('.perfil-form');
            const actionUrl = form.getAttribute('action'); // Certifique-se de que o 'action' está definido corretamente no formulário HTML
            const csrfToken = form.querySelector('[name="csrfmiddlewaretoken"]').value;
            const perfilId = this.getAttribute('data-perfil-id');
            const acao = this.getAttribute('data-acao');
    
            const formData = new FormData();
            formData.append('csrfmiddlewaretoken', csrfToken);
            formData.append('perfilId', perfilId);
            formData.append('acao', acao);
    
            console.log('Enviando requisição para:', actionUrl);
            console.log('Dados do formulário:', formData);
    
            fetch(actionUrl, {
                method: 'POST',
                body: formData,
                headers: {
                    'X-Requested-With': 'XMLHttpRequest'
                }
            })
            .then(response => response.json())
            .then(data => {
                console.log('Resposta do servidor:', data);
                if (data.error) {
                    alert(data.error);
                } else {
                    alert(data.message);
                    // Remove o perfil do DOM
                    const perfilElement = document.getElementById(`perfil-${perfilId}`);
                    if (perfilElement) {
                        perfilElement.remove();
                        console.log('Perfil removido do DOM.');

                    ajustarExibicaoPerfis();

                    } else {
                        console.error(`Elemento #perfil-${perfilId} não encontrado no DOM.`);
                    }
                }
            })
            .catch(error => {
                console.error('Erro ao enviar requisição:', error);
            });
        });
    });
</script>
<script>
document.addEventListener('DOMContentLoaded', function() {
    ajustarExibicaoPerfis();
});

function ajustarExibicaoPerfis() {
    const perfis = document.querySelectorAll('.figure');

    // Primeiro, esconde todos os perfis
    perfis.forEach(perfil => {
        perfil.style.display = 'none';
    });

    // Determina quais perfis devem ser exibidos
    let indicesParaExibir;
    if (perfis.length <= 3) {
        // Se houver 3 ou menos perfis, todos serão exibidos
        indicesParaExibir = Array.from({length: perfis.length}, (_, i) => i);
    } else {
        // Calcula os índices dos 3 perfis centrais para exibição
        const meio = Math.floor(perfis.length / 2);
        indicesParaExibir = [meio - 1, meio, meio + 1];
    }

    // Aplica desfoque e exibe os perfis conforme necessário
    perfis.forEach((perfil, index) => {
        if (indicesParaExibir.includes(index)) {
            perfil.style.display = ''; // Exibe o perfil
            // Aplica desfoque nos perfis das pontas (primeiro e último dos três)
            if (index === indicesParaExibir[0] || index === indicesParaExibir[indicesParaExibir.length - 1]) {
                perfil.classList.add('blur-effect');
                perfil.querySelectorAll('.like, .dislike').forEach(botao => botao.disabled = true);
            } else {
                perfil.classList.remove('blur-effect');
                perfil.querySelectorAll('.like, .dislike').forEach(botao => botao.disabled = false);
            }
        }
    });
}
</script>

    

{% endblock %}

app/usuarios/templates/profile-page.html
{% load static %} 
{% block static%}
<link rel="stylesheet" href="{% static 'usuarios/profile-page.css' %}">
{% endblock%}



{% block content%}
<body>
    <div class="container">
        <h1>Meu Perfil</h1>
        {% if foto %}
            <img id="profileImage" src="{{ foto }}" alt="Foto de perfil" class="profile-image">
        {% else %}
            <img id="profileImage"  src="{% static 'usuarios/profile_image_fixa.png' %}" alt="Foto de perfil padrão" class="profile-image">
        {% endif %}
        <form id="profileForm" method="post" action="{% url 'usuarios:perfil' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="photo">Foto de Perfil:</label>
                <input type="file" id="photo" name="foto" onchange="previewImage()">
            </div>
            <div class="form-group">
                <label for="name">Nome:</label>
                <label for="name">{{ nome }}</label>
            </div>
            <div class="form-group">
                <label for="birthdate">Data de Nascimento:</label>
                <label for="birthdate">{{ data_de_nascimento }}</label>
            </div>
            <div class="form-group">
                <label for="descricao">Descrição:</label>
                <textarea type="text" id="descricao" name="descricao">{{ descricao }}</textarea>
            </div>
            <!-- Novo campo para a sexualidade -->
            <div class="form-group">
                <label for="sexo">Sexualidade:</label>
                <select id="sexo" name="sexo" class="form-control">
                    <option value="M">Masculino</option>
                    <option value="F">Feminino</option>
                    <option value="A">Ambos</option>
                    <option value="NADA">Nenhum display</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Salvar</button>
        </form>
    </div>
</body>
<script>
        function previewImage() {
            const fileInput = document.getElementById('photo');
            const profileImage = document.getElementById('profileImage');
            
            if (fileInput.files && fileInput.files[0]) {
                const reader = new FileReader();
                
                reader.onload = function(e) {
                    profileImage.src = e.target.result;
                };
                
                reader.readAsDataURL(fileInput.files[0]);
            }
        }
        </script>
</body>
</html>

{% endblock%}

app/usuarios/templates/signup-page.html
{% load static %}


{% block static %}
<link rel="stylesheet" href="{% static 'usuarios/signup-page.css' %}"> 
{% endblock %}


{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Cadastro</title>
    <!-- Adicione aqui suas referências a CSS e outros recursos -->
</head>
<body>
    <div class="main-cadastro">
        <div class="left"> 
            <h1>Faça seu cadastro na Puc-Match<br>E junte-se a milhares de alunos</h1>
        </div>
        <div class="right">
            <form id="cadastroForm" class="card-login" method="post" action="{% url 'usuarios:signup' %}">
                {% csrf_token %}
                {% if error %}
                    <p>{{ error }}</p>
                {% endif %}
                <div id="primeiraParte">
                    <div class="textfield">
                        <label for="email">Email</label>
                        <input type="text" name="email" placeholder="Email" required>
                    </div>
                    <div class="textfield">
                        <label for="nome">Nome</label>
                        <input type="text" name="nome" placeholder="Nome" required>
                    </div>
                    <div class="textfield">
                        <label for="senha">Senha</label>
                        <input type="password" name="senha" placeholder="Senha" required>
                    </div>
                    <div class="textfield">
                        <label for="confirmar">Confirmar senha</label>
                        <input type="password" name="confirmar_senha" placeholder="Confirmar Senha" required>
                    </div>
                    <button type="button" id="nextBtn">Próximo</button>
                </div>
                <div id="segundaParte" style="display: none;">
                    <div class="textfield">
                        <label for="cep">CEP</label>
                        <input type="text" name="cep" placeholder="CEP" maxlength="9" required id="cep">
                    </div>
                    <div class="textfield">
                        <label for="estado">Estado</label>
                        <input type="text" name="estado" placeholder="Estado" maxlength="50" required>
                    </div>
                    <div class="textfield">
                        <label for="cidade">Cidade</label>
                        <input type="text" name="cidade" placeholder="Cidade">
                    </div>
                    <div class="textfield">
                        <label for="bairro">Bairro</label>
                        <input type="text" name="bairro" placeholder="Bairro" required>
                    </div>
                    <div class="textfield">
                        <label for="rua">Rua</label>
                        <input type="text" name="rua" placeholder="Rua" required>
                    </div>
                    <button type="button" id="nextBtnEndereco">Próximo</button>
                </div>
                <div id="terceiraParte" style="display: none;">
                    <div class="textfield">
                        <label for="cpf">CPF</label>
                        <input type="text" name="cpf" placeholder="cpf" maxlength="14" required>
                    </div>
                    <div class="textfield">
                        <label for="data_nascimento">Data de Nascimento</label>
                        <input type="date" name="data_de_nascimento">
                    </div>
                    <div class="textfield">
                        <label for="matricula">Matrícula</label>
                        <input type="text" name="matricula" placeholder="matricula" required>
                    </div>
                    <div class="textfield">
                        <label for="curso">Curso</label>
                        <input type="text" name="curso" placeholder="curso" required>
                    </div>
                    <button type="submit" id="submitBtn">Finalizar Cadastro</button>
                </div>
            </form>
        </div>
    </div>
</body>
</html>
<script>

function validarEmail(emailFormulario) {
    let validarRegExNoEmail = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
    if (emailFormulario.match(validarRegExNoEmail)) {
        return true;
    } else {
        return false;
    }
}
function validarCPF(cpfFormulario) {
    let validarRegExNoCPF = /^\d{3}\.\d{3}\.\d{3}\-\d{2}$/;
    if (cpfFormulario.match(validarRegExNoCPF)) {
        return true;
    } else {
        return false;
    }
}
function validarIdade(dataNascimento) {
    let dataAtual = new Date();
    let dataNasc = new Date(dataNascimento);
    let idade = dataAtual.getFullYear() - dataNasc.getFullYear();
    let m = dataAtual.getMonth() - dataNasc.getMonth();
    if (m < 0 || (m === 0 && dataAtual.getDate() < dataNasc.getDate())) {
        idade--;
    }
    return idade >= 18;
}
document.getElementsByName('cpf')[0].addEventListener('input', function(event) {
    let cpf = event.target.value;
    cpf = cpf.replace(/\D/g, ""); // Remove qualquer coisa que não seja dígito
    cpf = cpf.replace(/(\d{3})(\d)/, "$1.$2"); // Adiciona um ponto depois do terceiro dígito
    cpf = cpf.replace(/(\d{3})(\d)/, "$1.$2"); // Adiciona um ponto depois do sexto dígito
    cpf = cpf.replace(/(\d{3})(\d{1,2})$/, "$1-$2"); // Adiciona um hífen depois do nono dígito
    event.target.value = cpf;
});
document.addEventListener('DOMContentLoaded', function() {
    document.getElementById('cep').addEventListener('blur', function(event) {
        var cep = event.target.value.replace(/\D/g, ''); // Remove tudo o que não é dígito
        if (cep.length === 8) { // Verifica se o CEP tem 8 dígitos
            fetch(`https://viacep.com.br/ws/${cep}/json/`)
                .then(response => response.json())
                .then(data => {
                    if (!("erro" in data)) { 
                        document.getElementsByName('rua')[0].value = data.logradouro;
                        document.getElementsByName('bairro')[0].value = data.bairro;
                        document.getElementsByName('cidade')[0].value = data.localidade;
                        document.getElementsByName('estado')[0].value = data.uf;
                    } else {
                        alert("CEP não encontrado.");
                    }
                })
                .catch(() => alert("Não foi possível buscar o CEP."));
        } else {
            alert("CEP inválido.");
        }
    });
    var nextBtn = document.getElementById('nextBtn');
    if (nextBtn) {
        nextBtn.addEventListener('click', function(event) {
            event.preventDefault();
            var email = document.getElementsByName('email')[0];
            var nome = document.getElementsByName('nome')[0];
            var senha = document.getElementsByName('senha')[0];
            var confirmar_senha = document.getElementsByName('confirmar_senha')[0];

            email.style.border = '';
            nome.style.border = '';
            senha.style.border = '';
            confirmar_senha.style.border = '';

            if (nome.value && validarEmail(email.value) && senha.value && confirmar_senha.value && senha.value === confirmar_senha.value) {
                document.getElementById('primeiraParte').style.display = 'none';
                document.getElementById('segundaParte').style.display = 'flex';
            } else {
                if (senha.value !== confirmar_senha.value) {
                    senha.style.border = '1px solid red';
                    confirmar_senha.style.border = '1px solid red';
                } else {
                    if (!validarEmail(email.value)) email.style.border = '1px solid red';
                    if (!nome.value) nome.style.border = '1px solid red';
                    if (!senha.value) senha.style.border = '1px solid red';
                    if (!confirmar_senha.value) confirmar_senha.style.border = '1px solid red';
                }
            }
        });
    } else {
        console.error('Element with ID "nextBtn" was not found.');
    }

    var nextBtnEndereco = document.getElementById('nextBtnEndereco');
    if (nextBtnEndereco) {
        nextBtnEndereco.addEventListener('click', function(event) {
            event.preventDefault();

            var cep = document.getElementsByName('cep')[0];
            var estado = document.getElementsByName('estado')[0];
            var cidade = document.getElementsByName('cidade')[0];
            var bairro = document.getElementsByName('bairro')[0];
            var rua = document.getElementsByName('rua')[0];

            cep.style.border = '';
            estado.style.border = '';
            cidade.style.border = '';
            bairro.style.border = '';
            rua.style.border = '';

            if (cep.value && estado.value && cidade.value && bairro.value && rua.value) {
                document.getElementById('segundaParte').style.display = 'none';
                document.getElementById('terceiraParte').style.display = 'flex';
            } else {
                if (!cep.value) cep.style.border = '1px solid red';
                if (!estado.value) estado.style.border = '1px solid red';
                if (!cidade.value) cidade.style.border = '1px solid red';
                if (!bairro.value) bairro.style.border = '1px solid red';
                if (!rua.value) rua.style.border = '1px solid red';
            }
        });
    } else {
        console.error('Element with ID "nextBtnEndereco" was not found.');
    }

    var submitBtn = document.getElementById('submitBtn');
    if (submitBtn) {
        submitBtn.addEventListener('click', function(event) {
            event.preventDefault();
        
            var cpf = document.getElementsByName('cpf')[0];
            var dataNascimento = document.getElementsByName('data_de_nascimento')[0];
        
            cpf.style.border = '';
            dataNascimento.style.border = '';
        
            if (validarCPF(cpf.value) && validarIdade(dataNascimento.value)) {
                document.getElementById('cadastroForm').submit();
            } else {
                if (!validarCPF(cpf.value)) cpf.style.border = '1px solid red';
                if (!validarIdade(dataNascimento.value)) dataNascimento.style.border = '1px solid red';
            }
        });
    } else {
        console.error('Element with ID "submitBtn" was not found.');
    }
});
</script>
{% endblock %}